### ISSUE TITLE
Configs don't update

### ISSUE THREAD

**Issue by Fossil01** [EmbarkStudios/wireguard-ui#17]
So I am running the docker container with this docker-compose file:

```
version: "3"
services:
  wireguard-ui:
    container_name: wireguard-ui
    image: embarkstudios/wireguard-ui:latest
    entrypoint: /wireguard-ui
    privileged: true
    ports:
      - "8084:8080"
      - "5555:5555"
    environment:
      data-dir: '/data'
      wg-endpoint: 'MY_EXTERNAL_IP:51820'
    # Volumes store your data between container upgrades
    volumes:
      - '/opt/dockers/wireguard-ui/data:/data'
    restart: unless-stopped
```

And I can access the webui at port 8084, create configs, but the config always contains: Endpoint = 127.0.0.1:51820 and Address = 172.31.255.1.

How do I set these?

**Comment by freddd** [comment]
Hi @Fossil01,

Thank you for creating an issue. Looking at the `docker-compose`-file that you supplied, you have got `wg-endpoint` under `environment` but it's a flag (https://github.com/EmbarkStudios/wireguard-ui/blob/master/server.go#L42) and needs to be provided in the `command` section, see example below:

```
version: "3"
services:
  wireguard-ui:
    container_name: wireguard-ui
    image: embarkstudios/wireguard-ui:latest
    entrypoint: /wireguard-ui
    command: ["--wg-endpoint", "MY_EXTERNAL_IP:51820"]
    privileged: true
    ports:
      - "8084:8080"
      - "5555:5555"
    environment:
      data-dir: '/data'
    # Volumes store your data between container upgrades
    volumes:
      - '/opt/dockers/wireguard-ui/data:/data'
    restart: unless-stopped
```

I will close the issue, feel free to reopen it if you are still experiencing issues after the suggested fix.
